#!/bin/bash
#
# Startup script
#
# chkconfig: 345 60 20
# description: Starts/stops our daemon
# processname: registrar_agent

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog=registrar_agent
executable=/usr/sbin/$prog
config=/etc/$prog/config.ini

lockfile=/var/lock/subsys/$prog
pidfile=/var/run/$prog/$prog.pid

start() {
	echo -n $"Starting $prog: "
	if  status -p $pidfile $prog 2>&1 > /dev/null ; then
		echo -n $"already started" && warning
		echo
		return 0
	fi
	daemon --user=$prog python $executable -p $pidfile -c $config 2>/dev/null
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}

stop() {
	echo -n $"Shutting down $prog: "
	if ! status -p $pidfile $prog 2>&1 > /dev/null ; then
		echo -n $"already stopped" && warning
		echo
		return 0
	fi
	killproc -p $pidfile -d 5
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
	return $RETVAL
}

# See how we were called.
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        status)
                status -p $pidfile $prog
                RETVAL=$?
                ;;
        restart)
                stop
                start
                ;;
        condrestart)
                if [ -f $pidfile ] ; then
                        stop
                        start
                fi
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|condrestart|status}"
                RETVAL=2
esac

exit $RETVAL

